### PR TITLE
Use the stack displayName when calling the cdk deploy command

### PR DESCRIPTION
**Pull request by ollyfg**
I'm sure you've noticed this, but there are warnings in the later 1.x versions of `cdk` that tell you to start using the path-style resource names (called `displayName` in the manifest and your cdk stack model). Eg. You should now use `cdk deploy myStage/myStack/mySubstack` instead of `cdk deploy myStageMyStackMySubstack`.

I have recently upgraded to cdk 2.x which now _requires_ you to use these display names, otherwise returning the error `No stacks match the name(s) xxx`.

I've made a one-line tweak to use the new display names.

Depending on what version of `cdk` you use you may or may not want to merge this, but I thought I'd at least pop it here in case it's helpful to anyone else!

### CODE REVIEW

**Comment by laimonassutkus** [comment]
@ollyfg thanks for your 3rd PR! Yep, noticed this, and yep, I agree with your PR. 
I think this could be potentially a breaking change for some people, hence, I would ask you to update the VERSION file to 3.0.0 and update the HISTORY.md file with a few sentences from this PR comment. Thanks!

**Review by laimonassutkus — CHANGES_REQUESTED** [review]
Missing updates in VERSION and HISTORY.md files. Suggest bumping the version to 3.0.0.

**Comment by ollyfg** [comment]
There you go!

**Review by laimonassutkus — APPROVED** [review]

**Comment by laimonassutkus** [comment]
Merged.

**Pull request merged**
